### ISSUE TITLE
make instructions skippable

### ISSUE THREAD

**Issue by szorowi1** [nivlab/jspsych-demos#28]
### Tasks
- [ ] Horizons task
- [x] Modified risk sensitivity task
- [x] Pavlovian go/no-go task
- [x] Two-step task
